import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    backgroundColor: "black",
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  motionText: {
    fontSize: 25,
    color: "white",
    marginBottom: 50,
  },
  playerList: {
    width: "100%",
    height: "40%",
  },
  buttonView: {
    width: "100%",
    height: "20%",
    justifyContent: "center",
    alignItems: "center",
  },
  button: {
    margin: 10,
    width: "80%",
    height: "30%",
    backgroundColor: "#F7E2C1",
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  text: {
    fontSize: 25,
    color: "black",
  },
});

export default styles;

/* CSS - Cascading Style Sheet */
/* Palette color codes */
/* Palette URL: http://paletton.com/#uid=33x0u0kleqtbzEKgVuIpcmGtdhZ */

/* Feel free to copy&paste color codes to your application */


/* As hex codes */

// .color-primary-0 { color: #346388 }	/* Main Primary color */
// .color-primary-1 { color: #7FA4C0 }
// .color-primary-2 { color: #507C9D }
// .color-primary-3 { color: #1F4F74 }
// .color-primary-4 { color: #0E3A5C }

// .color-secondary-1-0 { color: #D3B047 }	/* Main Secondary color (1) */
// .color-secondary-1-1 { color: #FFE8A3 }
// .color-secondary-1-2 { color: #F5D473 }
// .color-secondary-1-3 { color: #B59126 }
// .color-secondary-1-4 { color: #8F6E0D }

// .color-secondary-2-0 { color: #D36F47 }	/* Main Secondary color (2) */
// .color-secondary-2-1 { color: #FFBDA3 }
// .color-secondary-2-2 { color: #F59873 }
// .color-secondary-2-3 { color: #B54F26 }
// .color-secondary-2-4 { color: #8F320D }



// /* As RGBa codes */

// .rgba-primary-0 { color: rgba( 52, 99,136,1) }	/* Main Primary color */
// .rgba-primary-1 { color: rgba(127,164,192,1) }
// .rgba-primary-2 { color: rgba( 80,124,157,1) }
// .rgba-primary-3 { color: rgba( 31, 79,116,1) }
// .rgba-primary-4 { color: rgba( 14, 58, 92,1) }

// .rgba-secondary-1-0 { color: rgba(211,176, 71,1) }	/* Main Secondary color (1) */
// .rgba-secondary-1-1 { color: rgba(255,232,163,1) }
// .rgba-secondary-1-2 { color: rgba(245,212,115,1) }
// .rgba-secondary-1-3 { color: rgba(181,145, 38,1) }
// .rgba-secondary-1-4 { color: rgba(143,110, 13,1) }

// .rgba-secondary-2-0 { color: rgba(211,111, 71,1) }	/* Main Secondary color (2) */
// .rgba-secondary-2-1 { color: rgba(255,189,163,1) }
// .rgba-secondary-2-2 { color: rgba(245,152,115,1) }
// .rgba-secondary-2-3 { color: rgba(181, 79, 38,1) }
// .rgba-secondary-2-4 { color: rgba(143, 50, 13,1) }



// /* Generated by Paletton.com © 2002-2014 */
// /* http://paletton.com */